complete kata 6 get comments by articleid
imaa04/be-nc-news-i pull request #6
Opened 2023-11-22 12:12 UTC by imaa04

2023-11-22 13:52 UTC, johnhutcheon requested changes
Hey Ima, just left some feedback if you could amend your testing and add the ones I've mentioned please 👍

2023-11-22 13:52 UTC, johnhutcheon commented on __tests__/app.test.js
> +        expect(comment.article_id).toBe(1);
I would expect this test to also show that each comment has the following properties:
comment_id
votes
created_at
author
body

2023-11-22 13:52 UTC, johnhutcheon commented on __tests__/app.test.js
> +          });
Missing a few more tests here- what would happen if we sent a get request to `api/articles/banana/comments` ?
And what would we expect if its a valid ID but the article has no comments?

2023-11-23 09:17 UTC, nickkagame requested changes
Hi Ima,  Good testing and good work generally.  Just need to add code to check whether an article exists so that you know what error code to send back., Think back to stephen's lecture on Tuesday! He showed exactly what to do.

2023-11-23 09:17 UTC, nickkagame commented on __tests__/app.test.js
> +        expect(response.body.msg).toBe("this article doesn't have a comment");
Dunno if this is a article that exists?  So maybe the error message should say that.

2023-11-23 09:17 UTC, nickkagame commented on __tests__/app.test.js
> +      .expect(404)
This should be a 200

2023-11-23 09:17 UTC, nickkagame commented on __tests__/app.test.js
> +      .expect(404)
The article exists but the article has no comments.  it is a valid response to get.

2023-11-23 09:17 UTC, nickkagame commented on models/articles.models.js
> +    .query(
You need to check if the article exists in order to determine whether the empty array being returned is due to there being no comments, or due to the article not existing.  Think back to Stephens Tuesday lecture!

2023-11-23 12:34 UTC, nickkagame approved these changes
Nice work Ima! See my comment for a small suggested edit.

2023-11-23 12:34 UTC, nickkagame commented on models/articles.models.js
> +          return Promise.reject({status: 200, msg: 'this article has no comments'})
Here you can just send back the empty array for the 200 no comments. So you can remove the condition

2023-11-23 14:33 UTC, merged